### ISSUE TITLE
Outbound-In NAT for port translation from the Internet to Internal services

### ISSUE THREAD

**Issue by milestone1201** [PaloAltoNetworks/HomeSkillet#3]
Could we add the optional ability to create an outbound-in (2-Zone firewall) translation for inside addresses to be accessible from the outside. Especially if we only have one outside IP, but want to forward different ports to different IPs internally. Example: vCenter, Plex Server, Synology NAS, etc. This would help when remotely accessing specific things from anywhere.

**Comment by scotchoaf** [comment]
This is a great idea but will require a new smaller skillet. Talking with our support team last week to finally look at this and have a collection of NAT skillets to simplify configuration
